### Obtener todas las recetas
GET http://localhost:8080/api/recipes
Accept: application/json

### Obtener receta por ID
GET http://localhost:8080/api/recipes/1
Accept: application/json

### Crear receta
POST http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

    {
        "name": "Bizcocho de Yogur",
        "description": "Bizcocho esponjoso y fácil con yogur.",
        "instructions": "1. Mezclar yogur, azúcar, aceite, huevos y harina. 2. Verter en un molde y hornear a 180°C durante 35 minutos.",
        "time": 45,
        "src":"https://i.blogs.es/6859eb/bizcocho_yogur_4_3/1200_900.jpg"
    }


 

### Actualizar receta
PUT http://localhost:8080/api/recipes/1
Content-Type: application/json
Accept: application/json

{
  "name": "Tortilla de patatas mejorada",
  "description": "¡Ahora más jugosa!",
  "instructions": "Sigue igual, pero usa aceite de oliva virgen extra.",
  "src": "https://ejemplo.com/tortilla2.jpg",
  "time": 30.0
}

### Eliminar receta
DELETE http://localhost:8080/api/recipes/1
